# defindo script
$script_mysql = <<-SCRIPT
apt-get update && \
apt-get install -y mysql-server-5.7 && \
mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT




Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    # configurando multiplas maquinas no  mesmo vagrant file

    # maquina mysql
    config.vm.define "mysql" do |mysql|
    
        mysql.vm.network "public_network", ip: "192.168.1.24"

        mysql.vm.synced_folder "./configs", "/configs"
    
    
        mysql.vm.synced_folder ".", "/vagrant", disabled: true
    
       
        mysql.vm.provision "shell", inline: "cat /configs/teste.pub >> .ssh/authorized_keys"
    
    
        mysql.vm.provision "shell", inline: $script_mysql
         
        
        mysql.vm.provision "shell", inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    
     
        mysql.vm.provision "shell", inline: "service mysql restart"
      end
      

    # Maquina php
    config.vm.define "phpweb" do |phpweb|

        phpweb.vm.network "forwarded_port", guest: 8888, host: 8888

        # ip sempre diferente
        phpweb.vm.network "public_network", ip: "192.168.1.25"

        # instalando puppet
        phpweb.vm.provision "shell", inline: "apt-get update && apt-get install -y puppet"
        # apontando a configuração que o puppet ira executar
        phpweb.vm.provision "puppet" do |puppet|
          puppet.manifests_path = "./configs/manifests"
          puppet.manifest_file = "phpweb.pp"
        end
    end
    
    config.vm.define "mysqlserver" do |mysqlserver|
      mysqlserver.vm.network "public_network", ip: "192.168.1.22"
      mysqlserver.vm.provision "shell", inline: "cat /vagrant/configs/teste.pub >> .ssh/authorized_keys"
    end
    # configurando maquina virtual com ansible,  
    config.vm.define "ansible" do |ansible|
      ansible.vm.network "public_network", ip: "192.168.1.26"
      # copia a chave PRIVADA gerada aqui para a pasta vagrant da maquina virtual ansible e muda as permissoes do arquivo da chave
      ansible.vm.provision "shell", 
      inline: "cp /vagrant/teste /home/vagrant && /
      chmod 600 /home/vagrant/teste
      "

      ansible.vm.provision "shell", 
      inline: "apt-get update && \
      sudo apt install -y software-properties-common && \
      sudo add-apt-repository --yes --update ppa:ansible/ansible && \
      sudo apt install ansible"
      
    end
  
    end