

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"




    # Definindo memoria cpu 
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      
      # definindo um SO diferente para uma determinada maquina
      config.vm.define "memcached" do |memcached|
        memcached.vm.box = "centos/7"
        memcached.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.name = "centos7_memcached"
        end

    config.vm.define "mysqlserver" do |mysqlserver|
      mysqlserver.vm.network "public_network", ip: "192.168.1.22"
      mysqlserver.vm.provision "shell", inline: "cat /vagrant/configs/teste.pub >> .ssh/authorized_keys"
    end

    # configurando maquina virtual com ansible,  
    config.vm.define "ansible" do |ansible|
      ansible.vm.network "public_network", ip: "192.168.1.26"

      ansible.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
        vb.name = "ansible__maquinavirtual"
      end
      # copia a chave PRIVADA gerada aqui para a pasta vagrant da maquina virtual ansible e muda as permissoes do arquivo da chave
      ansible.vm.provision "shell", 
      inline: "cp /vagrant/teste  /home/vagrant && \
              chmod 600 /home/vagrant/teste && \
              chown vagrant:vagrant /home/vagrant/teste"

      ansible.vm.provision "shell", 
      inline: "sudo apt-get update && \
      sudo apt install -y ansible"
      ansible.vm.provision "shell", 
      inline: "ansible-playbook -i /vagrant/configs/ansible/hosts \
       /vagrant/configs/ansible/playbook.yml"

      
    end
  
    end