# defindo script
$script_mysql = <<-SCRIPT
apt-get update && \
apt-get install -y mysql-server-5.7 && \
mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT




Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    # configurando multiplas maquinas no  mesmo vagrant file

    # maquina mysql
    config.vm.define "mysql" do |mysql|
    
        mysql.vm.network "public_network", ip: "192.168.1.24"

        mysql.vm.synced_folder "./configs", "/configs"
    
    
        mysql.vm.synced_folder ".", "/vagrant", disabled: true
    
       
        mysql.vm.provision "shell", inline: "cat /configs/teste.pub >> .ssh/authorized_keys"
    
    
        mysql.vm.provision "shell", inline: $script_mysql
         
        
        mysql.vm.provision "shell", inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    
     
        mysql.vm.provision "shell", inline: "service mysql restart"
      end
         #   Maquina php
      config.vm.define "phpweb" do |phpweb|
        # ip sempre diferente
        phpweb.vm.network "public_network", ip: "192.168.1.25"
      end
  end